### ISSUE TITLE
Would it be appropriate to propose Awkward Array as an array library on NumPy's homepage?

### ISSUE THREAD

**Issue by jpivarski** [numpy/numpy.org#632]
The numpy.org homepage has a list of array libraries that are either alternatives to or build on NumPy:

<img src="https://user-images.githubusercontent.com/1852447/225064954-3151c386-8e60-4537-985a-2c07140c0697.png" width=600>

[Awkward Array](https://awkward-array.org/) fits into this category (it builds on NumPy; not an alternative to it). If this is not considered shameless promotion (I'm its original author), could I open a PR to add it to https://github.com/numpy/numpy.org/blob/main/content/en/tabcontents.yaml?

It would look like this

```yaml
  - title: Awkward Array
    text: Manipulate JSON-like data with NumPy-like idioms.
    img: /images/content_images/arlib/awkward.svg
    alttext: awkward
    url: https://awkward-array.org/
```

where `awkward.svg` is [this SVG file](https://github.com/scikit-hep/awkward/blob/main/docs-img/logo/logo.svg).

Then there's a question of where it should go in the list, what is its order relative to the other libraries. My first impression was that they're sorted by popularity, but maybe not: I just checked their numbers of GitHub stars and it seems random. I'd be happy enough putting it at the end of the list.

| Library | GitHub stars (March 2023) |
|:--|--:|
| Dask | 10800 |
| CuPy | 6700 |
| JAX | 22200 |
| xarray | 2900 |
| Sparse | 492 |
| PyTorch | 63700 |
| TensorFlow | 172000 |
| MXNet | 20300 |
| Arrow | 11300 |
| xtensor | 2900 |
| XND | 80 |
| uarray | 96 |
| tensorly | 1400 |
| Awkward Array | 658 |

Any thoughts on this?

In the past, @rgommers has added libraries to this list (https://github.com/czgdp1807/numpy.org/commit/05e04624a6ae43aa7cc54afbd3c39c3f5a7c1d49), so maybe this is a question to him (non-exclusively)?
